### ISSUE TITLE
Truffle test failed on BancorConverter.js

### ISSUE THREAD

**Issue by hackfisher** [evolutionlandorg/bancor-contracts#15]
```
 1) verifies that getReturn returns the same amount as buy -> sell when converting between 2 connectors

    Events emitted during test:
    ---------------------------

    NewSmartToken(_token: 0x9922fbcd5d56028a14c6d09094e2edb38a3608cb)
    FeaturesAddition(_address: <indexed>, _features: 1)
    Issuance(_amount: 20000)
    Transfer(_from: <indexed>, _to: <indexed>, _value: 20000)
    Transfer(_from: <indexed>, _to: <indexed>, _value: 5000)
    Transfer(_from: <indexed>, _to: <indexed>, _value: 8000)
    OwnerUpdate(_prevOwner: <indexed>, _newOwner: <indexed>)
    Approval(_owner: <indexed>, _spender: <indexed>, _value: 500)

    ---------------------------
    2) verifies that Conversion event returns conversion fee after buying

    Events emitted during test:
    ---------------------------

    NewSmartToken(_token: 0x75d4b0406c8dbea9b61f8820bc832b376a800ce4)
    FeaturesAddition(_address: <indexed>, _features: 1)
    Issuance(_amount: 20000)
    Transfer(_from: <indexed>, _to: <indexed>, _value: 20000)
    Transfer(_from: <indexed>, _to: <indexed>, _value: 5000)
    Transfer(_from: <indexed>, _to: <indexed>, _value: 8000)
    OwnerUpdate(_prevOwner: <indexed>, _newOwner: <indexed>)
    ConversionFeeUpdate(_prevFee: 0, _newFee: 3000)
    Approval(_owner: <indexed>, _spender: <indexed>, _value: 500)

    ---------------------------
    3) verifies that Conversion event returns conversion fee after selling

    Events emitted during test:
    ---------------------------

    NewSmartToken(_token: 0xddf8a1bf88017f519cbad90a21612354ebfdb815)
    FeaturesAddition(_address: <indexed>, _features: 1)
    Issuance(_amount: 20000)
    Transfer(_from: <indexed>, _to: <indexed>, _value: 20000)
    Transfer(_from: <indexed>, _to: <indexed>, _value: 5000)
    Transfer(_from: <indexed>, _to: <indexed>, _value: 8000)
    OwnerUpdate(_prevOwner: <indexed>, _newOwner: <indexed>)
    ConversionFeeUpdate(_prevFee: 0, _newFee: 3000)
    Approval(_owner: <indexed>, _spender: <indexed>, _value: 500)

    ---------------------------
    ✓ should throw when attempting to get the return with an invalid from token adress (1092ms)
    ✓ should throw when attempting to get the return with an invalid to token address (999ms)
    ✓ should throw when attempting to get the return with identical from/to addresses (1058ms)
    ✓ should throw when attempting to get the purchase return while the converter is not active (860ms)
    ✓ should throw when attempting to get the purchase return with a non connector address (1080ms)
    ✓ should throw when attempting to get the purchase return while purchasing with the connector is disabled (1055ms)
    ✓ should throw when attempting to get the sale return while the converter is not active (892ms)
    ✓ should throw when attempting to get the sale return with a non connector address (1096ms)
    4) verifies that convert returns a valid amount

    Events emitted during test:
    ---------------------------

    NewSmartToken(_token: 0x3e5f689628b8620880ee8ed4765e3a70983abda7)
    FeaturesAddition(_address: <indexed>, _features: 1)
    Issuance(_amount: 20000)
    Transfer(_from: <indexed>, _to: <indexed>, _value: 20000)
    Transfer(_from: <indexed>, _to: <indexed>, _value: 5000)
    Transfer(_from: <indexed>, _to: <indexed>, _value: 8000)
    OwnerUpdate(_prevOwner: <indexed>, _newOwner: <indexed>)
    Approval(_owner: <indexed>, _spender: <indexed>, _value: 500)

    ---------------------------
    5) verifies that selling right after buying does not result in an amount greater than the original purchase amount

    Events emitted during test:
    ---------------------------

    NewSmartToken(_token: 0xc9f04e42e8f58b42c14c310c607c06e94bd85beb)
    FeaturesAddition(_address: <indexed>, _features: 1)
    Issuance(_amount: 20000)
    Transfer(_from: <indexed>, _to: <indexed>, _value: 20000)
    Transfer(_from: <indexed>, _to: <indexed>, _value: 5000)
    Transfer(_from: <indexed>, _to: <indexed>, _value: 8000)
    OwnerUpdate(_prevOwner: <indexed>, _newOwner: <indexed>)
    Approval(_owner: <indexed>, _spender: <indexed>, _value: 500)

    ---------------------------
    6) verifies that buying right after selling does not result in an amount greater than the original sale amount

    Events emitted during test:
    ---------------------------

    NewSmartToken(_token: 0x85d1a0e795475ede38071f386e5d0bd94cc81bb1)
    FeaturesAddition(_address: <indexed>, _features: 1)
    Issuance(_amount: 20000)
    Transfer(_from: <indexed>, _to: <indexed>, _value: 20000)
    Transfer(_from: <indexed>, _to: <indexed>, _value: 5000)
    Transfer(_from: <indexed>, _to: <indexed>, _value: 8000)
    OwnerUpdate(_prevOwner: <indexed>, _newOwner: <indexed>)

    ---------------------------
    ✓ should throw when attempting to convert with an invalid from token adress (1217ms)
    ✓ should throw when attempting to convert with an invalid to token address (1232ms)
    ✓ should throw when attempting to convert with identical from/to addresses (1174ms)
    ✓ should throw when attempting to convert with 0 minimum requested amount (1342ms)
    ✓ should throw when attempting to convert when the return is smaller than the minimum requested amount (1309ms)
    7) verifies balances after buy

    Events emitted during test:
    ---------------------------

    NewSmartToken(_token: 0xd9b31e216aa710d484b948a183dcb881fe87d217)
    FeaturesAddition(_address: <indexed>, _features: 1)
    Issuance(_amount: 20000)
    Transfer(_from: <indexed>, _to: <indexed>, _value: 20000)
    Transfer(_from: <indexed>, _to: <indexed>, _value: 5000)
    Transfer(_from: <indexed>, _to: <indexed>, _value: 8000)
    OwnerUpdate(_prevOwner: <indexed>, _newOwner: <indexed>)
    Approval(_owner: <indexed>, _spender: <indexed>, _value: 500)

    ---------------------------
    ✓ should throw when attempting to buy while the converter is not active (1027ms)
    ✓ should throw when attempting to buy with a non connector address (1251ms)
    ✓ should throw when attempting to buy while the purchase yields 0 return (1189ms)
    ✓ should throw when attempting to convert while conversions are disabled (1348ms)
    ✓ should throw when attempting to buy with gas price higher than the universal limit (1194ms)
    ✓ should throw when attempting to buy with 0 minimum requested amount (1241ms)
    ✓ should throw when attempting to buy while the connector purchases are disabled (1333ms)
    ✓ should throw when attempting to buy without first approving the converter to transfer from the buyer account in the connector contract (1052ms)
    8) verifies balances after sell

    Events emitted during test:
    ---------------------------

    NewSmartToken(_token: 0x108a5bad907b99f4b1c258c85d98eb42275fa25f)
    FeaturesAddition(_address: <indexed>, _features: 1)
    Issuance(_amount: 20000)
    Transfer(_from: <indexed>, _to: <indexed>, _value: 20000)
    Transfer(_from: <indexed>, _to: <indexed>, _value: 5000)
    Transfer(_from: <indexed>, _to: <indexed>, _value: 8000)
    OwnerUpdate(_prevOwner: <indexed>, _newOwner: <indexed>)

    ---------------------------
    ✓ should throw when attempting to sell while the converter is not active (891ms)
    ✓ should throw when attempting to sell with a non connector address (1201ms)
    ✓ should throw when attempting to sell while the sale yields 0 return (1121ms)
    ✓ should throw when attempting to sell with amount greater then the seller balance (1136ms)
    ✓ verifies that getReturn returns the same amount as getCrossConnectorReturn when converting between 2 connectors (1181ms)
    9) verifies that getCrossConnectorReturn returns the same amount as convert between 2 connectors

    Events emitted during test:
    ---------------------------

    NewSmartToken(_token: 0xbfddd6bf1849e0dd12f123ce4ca5c7486b914709)
    FeaturesAddition(_address: <indexed>, _features: 1)
    Issuance(_amount: 20000)
    Transfer(_from: <indexed>, _to: <indexed>, _value: 20000)
    Transfer(_from: <indexed>, _to: <indexed>, _value: 5000)
    Transfer(_from: <indexed>, _to: <indexed>, _value: 8000)
    OwnerUpdate(_prevOwner: <indexed>, _newOwner: <indexed>)
    Approval(_owner: <indexed>, _spender: <indexed>, _value: 500)

    ---------------------------


  79 passing (1m)
  9 failing

  1) Contract: BancorConverter
       verifies that getReturn returns the same amount as buy -> sell when converting between 2 connectors:
     Error: VM Exception while processing transaction: revert
      at Object.InvalidResponse (/usr/local/lib/node_modules/truffle/build/webpack:/~/web3/lib/web3/errors.js:38:1)
      at /usr/local/lib/node_modules/truffle/build/webpack:/~/web3/lib/web3/requestmanager.js:86:1
      at /usr/local/lib/node_modules/truffle/build/webpack:/packages/truffle-provider/wrapper.js:134:1
      at XMLHttpRequest.request.onreadystatechange (/usr/local/lib/node_modules/truffle/build/webpack:/~/web3/lib/web3/httpprovider.js:128:1)
      at XMLHttpRequestEventTarget.dispatchEvent (/usr/local/lib/node_modules/truffle/build/webpack:/~/xhr2/lib/xhr2.js:64:1)
      at XMLHttpRequest._setReadyState (/usr/local/lib/node_modules/truffle/build/webpack:/~/xhr2/lib/xhr2.js:354:1)
      at XMLHttpRequest._onHttpResponseEnd (/usr/local/lib/node_modules/truffle/build/webpack:/~/xhr2/lib/xhr2.js:509:1)
      at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/truffle/build/webpack:/~/xhr2/lib/xhr2.js:469:1)
      at endReadableNT (_stream_readable.js:1056:12)
      at _combinedTickCallback (internal/process/next_tick.js:138:11)
      at process._tickCallback (internal/process/next_tick.js:180:9)

  2) Contract: BancorConverter
       verifies that Conversion event returns conversion fee after buying:
     Error: VM Exception while processing transaction: revert
      at Object.InvalidResponse (/usr/local/lib/node_modules/truffle/build/webpack:/~/web3/lib/web3/errors.js:38:1)
      at /usr/local/lib/node_modules/truffle/build/webpack:/~/web3/lib/web3/requestmanager.js:86:1
      at /usr/local/lib/node_modules/truffle/build/webpack:/packages/truffle-provider/wrapper.js:134:1
      at XMLHttpRequest.request.onreadystatechange (/usr/local/lib/node_modules/truffle/build/webpack:/~/web3/lib/web3/httpprovider.js:128:1)
      at XMLHttpRequestEventTarget.dispatchEvent (/usr/local/lib/node_modules/truffle/build/webpack:/~/xhr2/lib/xhr2.js:64:1)
      at XMLHttpRequest._setReadyState (/usr/local/lib/node_modules/truffle/build/webpack:/~/xhr2/lib/xhr2.js:354:1)
      at XMLHttpRequest._onHttpResponseEnd (/usr/local/lib/node_modules/truffle/build/webpack:/~/xhr2/lib/xhr2.js:509:1)
      at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/truffle/build/webpack:/~/xhr2/lib/xhr2.js:469:1)
      at endReadableNT (_stream_readable.js:1056:12)
      at _combinedTickCallback (internal/process/next_tick.js:138:11)
      at process._tickCallback (internal/process/next_tick.js:180:9)

  3) Contract: BancorConverter
       verifies that Conversion event returns conversion fee after selling:
     Error: VM Exception while processing transaction: revert
      at Object.InvalidResponse (/usr/local/lib/node_modules/truffle/build/webpack:/~/web3/lib/web3/errors.js:38:1)
      at /usr/local/lib/node_modules/truffle/build/webpack:/~/web3/lib/web3/requestmanager.js:86:1
      at /usr/local/lib/node_modules/truffle/build/webpack:/packages/truffle-provider/wrapper.js:134:1
      at XMLHttpRequest.request.onreadystatechange (/usr/local/lib/node_modules/truffle/build/webpack:/~/web3/lib/web3/httpprovider.js:128:1)
      at XMLHttpRequestEventTarget.dispatchEvent (/usr/local/lib/node_modules/truffle/build/webpack:/~/xhr2/lib/xhr2.js:64:1)
      at XMLHttpRequest._setReadyState (/usr/local/lib/node_modules/truffle/build/webpack:/~/xhr2/lib/xhr2.js:354:1)
      at XMLHttpRequest._onHttpResponseEnd (/usr/local/lib/node_modules/truffle/build/webpack:/~/xhr2/lib/xhr2.js:509:1)
      at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/truffle/build/webpack:/~/xhr2/lib/xhr2.js:469:1)
      at endReadableNT (_stream_readable.js:1056:12)
      at _combinedTickCallback (internal/process/next_tick.js:138:11)
      at process._tickCallback (internal/process/next_tick.js:180:9)

  4) Contract: BancorConverter
       verifies that convert returns a valid amount:
     Error: VM Exception while processing transaction: revert
      at Object.InvalidResponse (/usr/local/lib/node_modules/truffle/build/webpack:/~/web3/lib/web3/errors.js:38:1)
      at /usr/local/lib/node_modules/truffle/build/webpack:/~/web3/lib/web3/requestmanager.js:86:1
      at /usr/local/lib/node_modules/truffle/build/webpack:/packages/truffle-provider/wrapper.js:134:1
      at XMLHttpRequest.request.onreadystatechange (/usr/local/lib/node_modules/truffle/build/webpack:/~/web3/lib/web3/httpprovider.js:128:1)
      at XMLHttpRequestEventTarget.dispatchEvent (/usr/local/lib/node_modules/truffle/build/webpack:/~/xhr2/lib/xhr2.js:64:1)
      at XMLHttpRequest._setReadyState (/usr/local/lib/node_modules/truffle/build/webpack:/~/xhr2/lib/xhr2.js:354:1)
      at XMLHttpRequest._onHttpResponseEnd (/usr/local/lib/node_modules/truffle/build/webpack:/~/xhr2/lib/xhr2.js:509:1)
      at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/truffle/build/webpack:/~/xhr2/lib/xhr2.js:469:1)
      at endReadableNT (_stream_readable.js:1056:12)
      at _combinedTickCallback (internal/process/next_tick.js:138:11)
      at process._tickCallback (internal/process/next_tick.js:180:9)

  5) Contract: BancorConverter
       verifies that selling right after buying does not result in an amount greater than the original purchase amount:
     Error: VM Exception while processing transaction: revert
      at Object.InvalidResponse (/usr/local/lib/node_modules/truffle/build/webpack:/~/web3/lib/web3/errors.js:38:1)
      at /usr/local/lib/node_modules/truffle/build/webpack:/~/web3/lib/web3/requestmanager.js:86:1
      at /usr/local/lib/node_modules/truffle/build/webpack:/packages/truffle-provider/wrapper.js:134:1
      at XMLHttpRequest.request.onreadystatechange (/usr/local/lib/node_modules/truffle/build/webpack:/~/web3/lib/web3/httpprovider.js:128:1)
      at XMLHttpRequestEventTarget.dispatchEvent (/usr/local/lib/node_modules/truffle/build/webpack:/~/xhr2/lib/xhr2.js:64:1)
      at XMLHttpRequest._setReadyState (/usr/local/lib/node_modules/truffle/build/webpack:/~/xhr2/lib/xhr2.js:354:1)
      at XMLHttpRequest._onHttpResponseEnd (/usr/local/lib/node_modules/truffle/build/webpack:/~/xhr2/lib/xhr2.js:509:1)
      at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/truffle/build/webpack:/~/xhr2/lib/xhr2.js:469:1)
      at endReadableNT (_stream_readable.js:1056:12)
      at _combinedTickCallback (internal/process/next_tick.js:138:11)
      at process._tickCallback (internal/process/next_tick.js:180:9)

  6) Contract: BancorConverter
       verifies that buying right after selling does not result in an amount greater than the original sale amount:
     Error: VM Exception while processing transaction: revert
      at Object.InvalidResponse (/usr/local/lib/node_modules/truffle/build/webpack:/~/web3/lib/web3/errors.js:38:1)
      at /usr/local/lib/node_modules/truffle/build/webpack:/~/web3/lib/web3/requestmanager.js:86:1
      at /usr/local/lib/node_modules/truffle/build/webpack:/packages/truffle-provider/wrapper.js:134:1
      at XMLHttpRequest.request.onreadystatechange (/usr/local/lib/node_modules/truffle/build/webpack:/~/web3/lib/web3/httpprovider.js:128:1)
      at XMLHttpRequestEventTarget.dispatchEvent (/usr/local/lib/node_modules/truffle/build/webpack:/~/xhr2/lib/xhr2.js:64:1)
      at XMLHttpRequest._setReadyState (/usr/local/lib/node_modules/truffle/build/webpack:/~/xhr2/lib/xhr2.js:354:1)
      at XMLHttpRequest._onHttpResponseEnd (/usr/local/lib/node_modules/truffle/build/webpack:/~/xhr2/lib/xhr2.js:509:1)
      at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/truffle/build/webpack:/~/xhr2/lib/xhr2.js:469:1)
      at endReadableNT (_stream_readable.js:1056:12)
      at _combinedTickCallback (internal/process/next_tick.js:138:11)
      at process._tickCallback (internal/process/next_tick.js:180:9)

  7) Contract: BancorConverter
       verifies balances after buy:
     Error: VM Exception while processing transaction: revert
      at Object.InvalidResponse (/usr/local/lib/node_modules/truffle/build/webpack:/~/web3/lib/web3/errors.js:38:1)
      at /usr/local/lib/node_modules/truffle/build/webpack:/~/web3/lib/web3/requestmanager.js:86:1
      at /usr/local/lib/node_modules/truffle/build/webpack:/packages/truffle-provider/wrapper.js:134:1
      at XMLHttpRequest.request.onreadystatechange (/usr/local/lib/node_modules/truffle/build/webpack:/~/web3/lib/web3/httpprovider.js:128:1)
      at XMLHttpRequestEventTarget.dispatchEvent (/usr/local/lib/node_modules/truffle/build/webpack:/~/xhr2/lib/xhr2.js:64:1)
      at XMLHttpRequest._setReadyState (/usr/local/lib/node_modules/truffle/build/webpack:/~/xhr2/lib/xhr2.js:354:1)
      at XMLHttpRequest._onHttpResponseEnd (/usr/local/lib/node_modules/truffle/build/webpack:/~/xhr2/lib/xhr2.js:509:1)
      at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/truffle/build/webpack:/~/xhr2/lib/xhr2.js:469:1)
      at endReadableNT (_stream_readable.js:1056:12)
      at _combinedTickCallback (internal/process/next_tick.js:138:11)
      at process._tickCallback (internal/process/next_tick.js:180:9)

  8) Contract: BancorConverter
       verifies balances after sell:
     Error: VM Exception while processing transaction: revert
      at Object.InvalidResponse (/usr/local/lib/node_modules/truffle/build/webpack:/~/web3/lib/web3/errors.js:38:1)
      at /usr/local/lib/node_modules/truffle/build/webpack:/~/web3/lib/web3/requestmanager.js:86:1
      at /usr/local/lib/node_modules/truffle/build/webpack:/packages/truffle-provider/wrapper.js:134:1
      at XMLHttpRequest.request.onreadystatechange (/usr/local/lib/node_modules/truffle/build/webpack:/~/web3/lib/web3/httpprovider.js:128:1)
      at XMLHttpRequestEventTarget.dispatchEvent (/usr/local/lib/node_modules/truffle/build/webpack:/~/xhr2/lib/xhr2.js:64:1)
      at XMLHttpRequest._setReadyState (/usr/local/lib/node_modules/truffle/build/webpack:/~/xhr2/lib/xhr2.js:354:1)
      at XMLHttpRequest._onHttpResponseEnd (/usr/local/lib/node_modules/truffle/build/webpack:/~/xhr2/lib/xhr2.js:509:1)
      at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/truffle/build/webpack:/~/xhr2/lib/xhr2.js:469:1)
      at endReadableNT (_stream_readable.js:1056:12)
      at _combinedTickCallback (internal/process/next_tick.js:138:11)
      at process._tickCallback (internal/process/next_tick.js:180:9)

  9) Contract: BancorConverter
       verifies that getCrossConnectorReturn returns the same amount as convert between 2 connectors:
     Error: VM Exception while processing transaction: revert
      at Object.InvalidResponse (/usr/local/lib/node_modules/truffle/build/webpack:/~/web3/lib/web3/errors.js:38:1)
      at /usr/local/lib/node_modules/truffle/build/webpack:/~/web3/lib/web3/requestmanager.js:86:1
      at /usr/local/lib/node_modules/truffle/build/webpack:/packages/truffle-provider/wrapper.js:134:1
      at XMLHttpRequest.request.onreadystatechange (/usr/local/lib/node_modules/truffle/build/webpack:/~/web3/lib/web3/httpprovider.js:128:1)
      at XMLHttpRequestEventTarget.dispatchEvent (/usr/local/lib/node_modules/truffle/build/webpack:/~/xhr2/lib/xhr2.js:64:1)
      at XMLHttpRequest._setReadyState (/usr/local/lib/node_modules/truffle/build/webpack:/~/xhr2/lib/xhr2.js:354:1)
      at XMLHttpRequest._onHttpResponseEnd (/usr/local/lib/node_modules/truffle/build/webpack:/~/xhr2/lib/xhr2.js:509:1)
      at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/truffle/build/webpack:/~/xhr2/lib/xhr2.js:469:1)
      at endReadableNT (_stream_readable.js:1056:12)
      at _combinedTickCallback (internal/process/next_tick.js:138:11)
      at process._tickCallback (internal/process/next_tick.js:180:9)
```

**Comment by hackfisher** [comment]
It seems that all these tests have ```convert``` ops.
e.g.
```
let convertRes = await converter.convert(connectorTokenAddress, connectorTokenAddress2, 500, 1);
        let returnAmount2 = getConversionAmount(convertRes);
```
